dist: focal
sudo: false
language: python
compiler: gcc
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v
   - export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
script:
   - azulejo install -y all
   - pytest --cov=azulejo --capture=tee-sys -x
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
