sudo: false
language: python
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v
   - export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
script:
   - poetry run nox -s tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
