dist: focal
sudo: false
language: python
compiler: gcc
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v
   - export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
script:
   - azulejo install -y all
   - pytest -s tests/0cli_test.py
   - pytest -s tests/1file_test.py
   - pytest -s tests/2ingest_test.py
   - pytest -s tests/3installer_test.py
   - travis_wait 30 pytest -s tests/4homology_test.py
   - pytest -s tests/5synteny_test.py
   - pytest -s tests/6parquet_test.py
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
