dist: focal
sudo: false
language: python
compiler: gcc
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v
   - azulejo
script:
   - export NCPUS=$(grep -c ^processor /proc/cpuinfo)
   - echo "NCPUS = $NCPUS"
   - export MAKEFLAGS="-j $NCPUS"
   - export LOG_TO_PRINT=info
   - export SPINNER_UPDATE_PERIOD="5.0"
   - pytest tests/0cli_test.py
   - pytest tests/1file_test.py
   - pytest tests/2ingest_test.py
   - pytest tests/3installer_test.py
   - pytest -v tests/4homology_test.py
   - travis_wait 60 pytest -v tests/5synteny_test.py
   - pytest tests/6parquet_test.py
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
