dist: focal
sudo: false
language: python
compiler: gcc
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v --no-dev
   - pip install -v sh coverage[toml] nox pytest pytest-cov
   - free
   - df -h
script:
   - export NCPUS=$(grep -c ^processor /proc/cpuinfo)
   - export FREE_MB=$(free -m | grep Mem | awk '{print $3')
   - echo "${NCPUS) cpus, ${FREE_MB} MB free"
   - export MAKEFLAGS="-j $NCPUS"
   - export LOG_TO_PRINT=info
   - export SPINNER_UPDATE_PERIOD="5.0"
   - export TEST_DIR=/dev/shm/pytest
   - #pytest tests/0cli_test.py || travis_terminate 1;
   - pytest tests/1file_test.py::setup_datadir || travis_terminate 1;
   - mkdir $TEST_DIR
   - pytest --basetemp=$TEST_DIR tests/2ingest_test.py || travis_terminate 1;
   - rm -r $TEST_DIR; mkdir $TEST_DIR
   - pytest --basetemp=$TEST_DIR  tests/3installer_test.py || travis_terminate 1;
   - pytest tests/4homology_test.py || travis_terminate 1;
   - rm -r $TEST_DIR; mkdir $TEST_DIR
   - pytest --basetemp=$TEST_DIR  tests/5synteny_test.py || travis_terminate 1;
   - rm -r $TEST_DIR; mkdir $TEST_DIR
   - pytest --basetemp=$TEST_DIR  tests/6parquet_test.py || travis_terminate 1;
after_success:
  - echo "Should upload coverage here"
  - #bash <(curl -s https://codecov.io/bash) -X gcov
